version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        IMAGE_VERSION: ${IMAGE_VERSION:-latest}
    image: harveywei64/number-check:${IMAGE_VERSION}
    container_name: number-check-app
    ports:
      - "8080:8080"
    depends_on:
      - db

