name: Build and Publish

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build Docker image
        run: docker-compose build

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: number-check:latest

      - name: Install SSH
          run: sudo apt-get install openssh-client -y

      - name: SSH into Aliyun Server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.ALIYUN_SERVER_IP }}
            username: root
            key: ${{ secrets.ALIYUN_SSH_PRIVATE_KEY }}
            port: 22
            script: |
              docker stop number-check || true
              docker rm number-check || true
              docker pull number-check:latest
              docker run -d --name number-check -p 80:80 number-check:latest