name: Build and Publish

on:
  push:
    branches: [odd-or-even]

jobs:
  build-push-publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build Docker image
        run: IMAGE_VERSION=${{ env.IMAGE_TAG }} docker-compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker Image
        run: IMAGE_VERSION=${{ env.IMAGE_TAG }} docker-compose push

